#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh
source $(dirname $0)/utils.sh

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/git-tag-resource-request

cat > $payload <&0

configure_git $payload

parse_source $payload

export GIT_LFS_SKIP_SMUDGE=1 # We're just checking for commits and tags; we don't ever need to fetch LFS files here!
destination=$TMPDIR/git-tag-resource-repo-cache
clone_repo $destination --single-branch

update_tags
tags=$(get_tags)
filtered_tags=$(filter_tags "$tags" "$tag_filter")

commits=$(get_commits "$filtered_tags")

format_output() {
  local tags=($1)
  local commits=($2)

  log "Formatting output"

  output=""
  for i in ${!tags[@]}; do
    output+="{tag: \"${tags[$i]}\", commit: \"${commits[$i]}\"}"
  done

  echo "[$output]" | sed "s/}{/},{/g"
}

output=$(format_output "$filtered_tags" "$commits")

jq -n "$output" >&3
