#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh
source $(dirname $0)/utils.sh

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/git-tag-resource-request

cat > $payload <&0

configure_git $payload

parse_source $payload


jq -n "[{
  ref: \"$tag\",
  uri: \"$uri\"
  }]" >&3
