#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh
source $(dirname $0)/utils.sh

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/git-tag-resource-request.XXXXXX)

cat > $payload <&0

configure_git $payload

parse_source $payload
parse_version $payload

clone_repo $destination

checkout_commit $commit

#TODO Retrieve and use useful metadata
metadata_key="commit"
jq -n "{version: \"$commit\", metadata: [{name: \"commit\", value: \"$commit\"}]}" >&3
